[[start]]
== Getting Started

=== Installation

To get started using this great module, include it into your build:

[source,xml,subs=attributes+]
.Maven
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>{artifactId}</artifactId>
    <version>{version}</version>
</dependency>
----

[source,groovy,subs=attributes+]
.Gradle
----
repositories {
    maven {
        url "http://repo.serebryanskiy.site/"
    }
}
compile '{groupId}:{artifactId}:{version}'
----

Or download
http://repo.serebryanskiy.site/{groupId}/{artifactId}/{version}/{artifactId}-{version}.jar[library]
and add to your project.

=== Creating your first Excel document

Here is the simplest example to create an Excel document:

[source,groovy]
----
def workbook = new ExcelBuilder().build {
    sheet {
        row {
            cell {
                "test"
            }
        }
    }
}

workbook.write(new FileOutputStream(new File('sample.xlsx')))
----

As you might imagine from that example, a single sheet will be created with
the value of "test" in cell `A1`:

.Content file 'sample.xlsx'
[width="10",cols="1,4"]
|=======
|    |*A*

|*1* |test
|=======


NOTE: Groovy Excel Builder supports XLSX documents only, not the old XLS
format and supports streaming version of Workbook (SXSSFWorkbook) only.

In addition to writing the excel document directly to an output stream, you
can also just build the document and do what you want with it afterwards.

The Groovy Excel Builder provides several options and features for creating
documents. To learn more, continue on reading this documentation.

=== Creating your Excel document with dynamic data

[source,groovy]
----
def workbook = new ExcelBuilder().build {
    sheet {
        (1..6).each { number ->
            row {
                ('A'..'F').each { letter ->
                    cell {
                        "$number $letter"
                    }
                }
            }
        }
    }
}

workbook.write(new FileOutputStream(new File('dynamic_data.xlsx')))
----

.Content file 'dynamic_data.xlsx'
[width="65",cols="1,4,4,4,4,4,4"]
|=======
|    |*A* |*B* |*C* |*D* |*E* |*F*

|*1* |1 A |1 B |1 C |1 D |1 E |1 F
|*2* |1 A |2 B |2 C |2 D |2 E |2 F
|*3* |3 A |3 B |3 C |3 D |3 E |3 F
|*4* |4 A |4 B |4 C |4 D |4 E |4 F
|*5* |5 A |5 B |5 C |5 D |5 E |5 F
|*6* |6 A |6 B |6 C |6 D |6 E |6 F
|=======
